version: "3.4"
services:
    postgres:
        image: postgres:12.5
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: prismadb
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: PASSWORD
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
            # Persist data between up/down
            - postgresql:/var/lib/postgresql/data:delegated

            # When data volume is empty, start every scripts in folder in A-Z order
            - ./postgres/:/docker-entrypoint-initdb.d/

    adminer:
        image: adminer
        ports:
            - "8081:8080"
        depends_on:
            - postgres

volumes:
    postgresql:
